### PR TITLE
Updated icon according new toolbar icon spec

### PR DESCRIPTION
**Pull request by larz0**
Hi Glenn could you merge this once NJ merges my larz/toolbar-hover on Brackets? Let me know if you have any questions.

### CODE REVIEW

**Comment by gruehle** [comment]
Sweet, thanks @larz0!

Let me know if you have a better suggestion for the icon. I just grabbed the first thing that worked from the Noun Project.

**Comment by larz0** [comment]
@gruehle I've updated the icon to make it more like devdocs.io's favicon.

**Comment by gruehle** [comment]
Thank you! :+1:

**Comment by larz0** [comment]
NP @gruehle safe to merge now :)

**Pull request merged**
